### ISSUE TITLE
Research: Decentralize address-server

### ISSUE THREAD

**Issue by oed** [3box/3box#214]
Given that we have #209 implemented there is only one thing that needs to be stored in the address-server, and that is the link between your ethereum address and your DID. To decentralize this we could make a custom store that extends the *feed-store* but that you can only add to if you have a valid link consent signature. This would work fairly well, however the problem is that it would be easy to spam this db. 

To counteract spamming we could add a mandatory Proof-of-Work to each new entry. This would require everyone that wants to make their profile public to compute a small PoW that would take a couple of seconds, which should be fine for any user. However, an attacker would need to spend a lot of resources in order to spam the network.

The result of this research story should investigate the feasibility of this approach, or come up with a new one. It should also specify how to implement any potential solution.

**Comment by oed** [comment]
Sena:
Via Discord: could the databases be replicated in the future? either continuously,  with consensus about writes, or at least snapshotted for transparency?  or would this expose private information? i'm not knocking the approach, i think it's great, just wondering if  there's anything that could be done to make people more comfortable  about adopting it either making it fully decentralized, or at least forkable

**Comment by MrLuit** [comment]
I haven't really looked into the address server all that much, but wouldn't it be possible to use an Ethereum smart contract to act as a public database? From what I currently understand about the project, a simple Solidity mapping could do the trick.

**Comment by oed** [comment]
@MrLuit You're very much correct yes. However we explicitly want to avoid any on-chain transaction since it degrades the user experience. It's also harder to scale.

As a follow up to this issue, we have found a quite simple solution that we are content with. 
Right now a mapping from address -> DID is stored in your threebox. This means that any pinning node that pins your 3box data will be able to see this mapping. The solution is that basically the pinning node keeps track of these mappings and if someone sends the address to the "3box-pinning" pubsub room any pinning node that pins your box can reply with your DID :)

**Comment by MrLuit** [comment]
Thanks for following up on me! Reading your explanation made me take a look at the [linking process](https://github.com/3box/3box-address-server#link-an-ethereum-address-to-a-did) to try to understand how the address -> DID mapping is currently implemented, as well as finding out if it could be improved in some way. I have some thoughts and suggestions concerning the `consent_signature`, which I would like to share. _(these are all suggestions, some of my understanding is likely incorrect; don't be afraid to critise any of these thoughts!)_

## Formatting
Currently, the `personal_sign` signature body consists solely of plain text, which will (very likely) cause issues for devs when trying to generate or parse it. Requiring future signatures to be formatted using JSON will help us out a lot! Additionally, proper formatting (by defining things like format version) will likely prevent future compatibility issues caused by changes in the signature format.

## Replay attacks
**I might be in the wrong here**; but I believe the current consent signature **might be susceptible to replay attacks**. What's preventing a malicious party from re-broadcasting old signatures from users whom decided to change their DID by broadcasting a new signature? Since the signature doesn't seem to contain any nonce or timestamp data, I think there's **no way for a client to detect an outdated signature**.

Personally, I'm leaning towards a solution of including a timestamp, since such a timestamp would also allow applications to easily calculate how recent signatures were submitted, something which would not be possible in the same manner when using a nonce. 

Clients should reject signatures which either **contain future timestamps** (`signature_timestamp > current_timestamp`) or **are simply outdated** (`signature_timestamp < most_recent_timestamp(address)`).

## Unlinking
Partially due to the replay issue, there seems to be no proper way for an address to unlink their current DID. My suggested approach on implementing this feature would be to add an `action` property, which defines the signature's purpose (e.g. `link` or `unlink`). In case the value of `action` is `unlink`, no `did` property is required.

## Example Signature
```json
{
    "version": 1,
    "action": "link",
    "did": "did:muport:example",
    "client": "3box-web 1.0.0-release",
    "time": 1550068005146
}
```
Note: I added an optional `client` property, which might be used for debugging purposes. So many possibilities! 

---
Would love to hear some feedback! I'm trying to learn as much as possible about how the project works, in order to (hopefully) start working with it soon. That's also why I'm mainly concerned about decentralization and limitations. Feel free to correct me if I'm misunderstanding something 😄

**Comment by oed** [comment]
@MrLuit Thanks this is awesome! Just letting you know I've seen this and will get back to you with an in depth response soon.

**Comment by oed** [comment]
Thanks for doing a deep dive on this @MrLuit! I think most of what you said makes sense. I have some minor things I'd think would improve thing:

> Formatting

Right now we are doing `personal_sign` mostly because it looks good for the user in the wallet interface. A JSON structure like you say makes sense, mostly likely in the form of [eip712](https://eips.ethereum.org/EIPS/eip-712). However, we need to make sure that this is not more confusing for users.

> Replay attacks 

The cool thing about using orbitdb is that if we add the link to the users 3Box, it can at a later point be removed. This wouldn't require any additional signature from the user. However this doesn't cover for the use case when you want to associate your address to a new 3Box (having multiple 3Boxes seems undesirable), so timestamping as you suggest makes a lot of sense.


In the context of the above I also think that the ability to unlink is a good addition.
Feel free to ask any other questions!

Oh, and if you want to make this into a [3IP](https://github.com/3box/3box/blob/master/3IPs/3ip-0.md) that would be sweet 🙂

**Comment by oed** [comment]
This is now solved with Ceramic ;)
