### ISSUE TITLE
Write bounties for verification libs/services

### ISSUE THREAD

**Issue by oed** [3box/3box#334]

**Comment by michaelsena** [comment]
@oed I had mentioned on twitter to @joaoaguiam that we were going to bounty a few verified fields for 3box.io. He's interested but has a few questions. https://twitter.com/somemikesena/status/1062479255597211650

**Comment by oed** [comment]
See:
* https://github.com/3box/3box-js/issues/195
* https://github.com/3box/3box-js/issues/196
* https://github.com/3box/3box-js/issues/197

**Comment by joaoaguiam** [comment]
@michaelsena I talked with @oed on Discord and this is aligned with our conversation. 
I agree that implementing these verifiers on the 3box-js is the best place for that, so that all dApp developers can have the same interface for the verifiers.

**Comment by joaoaguiam** [comment]
Hey @oed, I have started working on this verification process and implemented the following way:
- Created a file `src/utils/verifiers.js` which exports the function `verifyGithub(did, proof)` where proof is the gistUrl. This function returns the github username or error if the file provided does not contain the DID received as argument
- Created a class `VerifiedAccounts` under `src/verifiedAccounts.js`. This class will implement the `add` and `get` for each of the verifiable accounts. The constructor of this class receives a 3Box and stores it locally, so that we can directly add it to the 3Box profile. The methods I added are:

  - `_requireBox()`
  - `async _addVerifiedPublicAccount(key, proof, verificationFunction)`
  - `async _getVerifiedPublicAccount(key, verificationFunction)`

  - `async addGithub(gistUrl)`
  - `async github()`

  This approach allows to easilly add new verified accounts if the verification function receives a did and a proof (string or object).

  @oed, when retrieving the github from the 3Box, should we get the content of the gist file and always verify that the github account is verified?

- Updated 3Box main class to create an instance of VerifiedAccounts in the constructor: `this.verifiedAccounts = new VerifiedAccounts(this);`.

  This way dApp developers can get the verified github account via `box.verifiedAccounts.github()`

I wasn't able to test it yet but wanted to have your first feedback before continuing the development. You can find the non-tested code here: [`verifiers.js`](https://gist.github.com/joaoaguiam/cfca66b182a92fe50f1914136bd3847f) and [`verifiedAccounts.js`](https://gist.github.com/joaoaguiam/59c5914c76e86375b527164250dbbdfc).

@michaelsena  and @oznekenzo, we may need to talk in order to know how the 3Box dApp should look like for the github and twitter verifications.

**Comment by michaelsena** [comment]
Thanks @joaoaguiam! I'll leave it to Oed to comment on the lib verification code, but I can point you to this story for the UI modal that will appear after a user clicks verify. https://github.com/3box/3box-dapp/issues/178. Essentially the user clicks a button which copies their DID strong to the clipboard and also opens another browser window with a new gist file open. The user only needs to paste the string and click save, and return to our app.

**Comment by oed** [comment]
Looks great @joaoaguiam some minor comments:
* You can base your code on this branch: https://github.com/3box/3box-js/tree/feat/verified-accounts Looks like it's mostly the same as what you did already 😄 
* If you make a PR based on that with tests that would be awesome!
* https://gist.github.com/joaoaguiam/59c5914c76e86375b527164250dbbdfc#file-verifiedaccounts-js-L34 looks wrong, it should save the `proof` right?
* Seems unnecessary to save the username: `this._box.public.set("verified_" + key, githubUsername);` 

> when retrieving the github from the 3Box, should we get the content of the gist file and always verify that the github account is verified?

I'd say yes! This would also remove the need to save the `verified_` as I mentioned above 🙂
