### ISSUE TITLE
Deploy local cache iframe page

### ISSUE THREAD

**Issue by oed** [3box/3box#335]

**Comment by oed** [comment]
Maybe it can be deployed on ipfs directly? 
See also: https://github.com/ipfs/in-web-browsers/issues/89

**Comment by zachferland** [comment]
We will create another story for possible future options. @oed and I discussed some of them. But for the first iteration we can do the following:

All the iframe code is in this repo - https://github.com/3box/3box-js-iframe. The iframe is two files iframe.html and iframe.js (included in the html file). For releases and versions we will just npm version and npm releases. Then we just need to upload those package folders on release to somewhere on our domain, and have each package version available. So we should end up with something like: `3box.io/3box-iframe/v0.0.1`, `3box.io/3box-iframe/v0.0.2`, etc or some similar naming scheme so that each iframe is available as `3box.io/3box-iframe/v0.0.1/iframe.html`

@c-castillo does this make sense? any additional thoughts? or thoughts on if that release process is simple enough?

**Comment by oed** [comment]
@zachferland would it maybe make sense to use a separate subdomain like `iframe.3box.io`? that way we can separate the localstorage access from the dapp.

**Comment by zachferland** [comment]
@oed  yeah lets use a subdomain
