### ISSUE TITLE
Merge airtable data into Notion 

### ISSUE THREAD

**Issue by dazuck** [3box/3box#409]

**Comment by jjperezaguinaga** [comment]
@dazuck sorry to comment on a closed thread, but how's Notion working for you guys? We want at some point anyone to be able to work and comment on our tools but Notion was charging us per user. We ended up switching from Slack + Asana to [Basecamp](https://basecamp.com/pricing) because it made way more sense for our 10+ team.

That being said, I can see working for <10 teams, would love to hear your thoughts. I imagine you still use ZenHub?
