### ISSUE TITLE
Thread access control strategies

### ISSUE THREAD

**Issue by Schwartz10** [3box/3box#595]
Right now, anyone can read and write to any thread. This ticket is meant to discuss different access control strategies for read and write permissions.

#558 moderators is a great first step in role-based access control, similar to Google Docs and what [textile is implementing](https://github.com/textileio/go-textile/issues/694). 

For our specific use case within Aragon, it would be great to determine roles directly from a smart contract and separate read/write permissions. @oed mentioned this would require changes to the pinning node and the client.

**Comment by oed** [comment]
Access controllers are defined by the interface in this repo: https://github.com/orbitdb/orbit-db-access-controllers
Creating an access controller based on a smart contract should be as simple as creating a new access controller type. This type then needs to be included in the 3box-js library as well as the 3box-pinning-node in order to work properly. 

An important thing to note is that orbitdb doesn't support revocation yet. This means that if a user has been added to the ACL they can't be removed. If they are removed e.g. don't hold a token anymore, this could potentially break the orbitdb system.

We are of course happy to help bring support for more types of access controllers into 3Box!

**Comment by michaelsena** [comment]
@oed how are you thinking about addressing @Schwartz10's question on separation of read and write permissions?

**Comment by oed** [comment]
Not sure what you mean exactly @michaelsena. Currently there isn't really any read permissions, as all threads are publicly readable. In the future as we add encryption to threads we can have more granular read permissions. However, since read permissions would be based on encryption it would be difficult to do this based on smart contract state.
