### ISSUE TITLE
Developer interviews

### ISSUE THREAD

**Issue by michaelsena** [3box/3box#771]

**Comment by dazuck** [comment]
@michaelsena @RachBLondon  happened upon this note while cleaning out personal backlog: "What's the customer journey in choosing where to store data and set up infra?"

Guessing this round of interviews is more focused on existing customers and their product painpoints, but if it makes sense to expand scope or to do another round in the near future, I think a clearly mapped out journey for relevant starutp devs (in our space or otherwise) from this earlier/wider vantage point will be valuable. 

Again, no urgency to adjust this round if it's not planned, just to have on the radar.

**Comment by michaelsena** [comment]
removing redundant
