### ISSUE TITLE
Define deploy node orchestration

### ISSUE THREAD

**Issue by msterle** [3box/3box#874]

**Comment by zachferland** [comment]
to follow up, earlier was mostly thinking about how we have an easy way to run a pinning node for different users, from single user own machine (or cloud), to one service/dapp, to infra provider and how we create different modules, default configs, configurable and have a spectrum of limited/agnostic tooling to maybe more tooling and more opinionated at greater scale. 

originally thought about just having a single docker image that included pinning and api, and both read from fs (ipfs and orbit), so that there was no orchestration or other configs, just a docker image consuming configs/file, more likely could have minimal service that runs not in a container as well. then get one click deploys too. I guess for most single users as well (ie just using for backups), dont need api either, so could easily run with single image anyways 

but @msterle  what you saying with minimal orchestration it could be fairly simple as well, and maybe more configurable, but less familiar with options there, not sure whats best, was just trying to weigh paths and maybe target which of those few dev user groups are mostly likely to run it first. But maybe we get both here, options to  run pinning with one image, and also as you were describing with orchestrating services

**Comment by msterle** [comment]
Original plan of bootstrapping off the 3box pinning node cluster does not capture all pubsub messages because it connects directly to one specific instance of the pinning node (at random) and so only receives the subset of pubsub messages sent to that instance.

The second alternative of using the rendezvous server **appears** to receive all pubsub messages from clients (because it peers directly with them), although there is a time period at client instantiation where the client is not connected to any peers (other than the bootstrapped 3box pinning node cluster). If a pin request is sent in that setup time, the private pinning node won't receive it.

It will likely be easier to overcome the limitation of the original plan, but for a first iteration, the second will be imnplemented.

![3box private node iter1.png](https://images.zenhubusercontent.com/5dc8d0458aade000013aa35d/93795dda-d253-40f0-ad1d-26bb6964d818)

![3box private node iter2.png](https://images.zenhubusercontent.com/5dc8d0458aade000013aa35d/16bfc607-0855-4b0e-ab65-f8312014c134)

**Comment by zachferland** [comment]
Followed up here instead, since going off direction of this issue and a bit long - https://www.notion.so/threebox/Technical-Planning-7ffee27704b34b20be8f01d5f6567ce1?p=d44528de3d0a4024b327bb003f5a7a59
