### ISSUE TITLE
Test: Clients will fetch identical blocks from all servers they are connected to

### ISSUE THREAD

**Issue by msterle** [3box/3box#973]

**Comment by msterle** [comment]
Experiment was run by fetching a 100-entry database against 2 and 4 pinning nodes sharing a blockstore.

```
| run | bootstrap nodes | blocksReceived | dupBlksReceived |
|-----|-----------------|----------------|-----------------|
| 1   | 2               | 140            | 68              |
| 2   | 2               | 214            | 83              |
| 3   | 2               | 204            | 41              |
| 4   | 2               | 214            | 93              |
| 5   | 2               | 168            | 19              |
| 6   | 2               | 206            | 83              |
| 7   | 4               | 428            | 199             |
| 8   | 4               | 432            | 263             |
| 9   | 4               | 415            | 262             |
| 10  | 4               | 432            | 288             |
```

**Comment by msterle** [comment]
@zachferland @oed 

To elaborate on how the above 2 strategies could look:

1. On the client side, extend the bitswap instance's `want-manager` module (https://github.com/ipfs/js-ipfs-bitswap/blob/master/src/want-manager/index.js) that keeps track of pinning node peers and only send wantlists to one of them (with appropriate retry logic).

This could be further optimized to split a wantlist across multiple pinning nodes, although the deep and narrow dag structure of orbit databases might not see the most optimization from this (I'm operating under the assumption that deep dags have blocks fetched sequentially because the dag is being traversed on the requester side)

The downside of this method is that it assumes that all pinning nodes have all content, which may not hold in the future.

2. A more general solution that doesn't require bitswap managing a list of pinning nodes:

- On the pinning nodes, implement a delegated dag traversal method so that clients can request all CIDs in a an orbit-db from a head CID. (Could be considered a very specific implementation of IPLD selectors)
- Now that all cids in the dag are known, implement the optimization from point #1, which would spread the requests across all nodes that responded to the dag traversal query (aka the pinning nodes with the content).

**Comment by oed** [comment]
How would 1 look like if we imagine that the orbit-db pinning cluster has a dynamic number of nodes? Is this out of scope of your considerations here?

This also assumes that the client has a js-ipfs node it's using as opposed to a js-ipfs-http-client. I don't think we want to make this assumption. In React Native we might end up using the http-client for example.

**Comment by msterle** [comment]
@oed the way I see pinning nodes scaling is along a list of predefined ids, so that we have a well-known bootstrap list (say, 10 ids). We might only have 2 of those up, but we can just ignore the ones that aren't available. This list could be tracked and updated periodically on the client side's bitswap implementation, but we'd keep all of them in the ipfs bootstrap config.

Applicable even now is how to update client config without without requiring an update to the `3box` package, and we'd also see it if we get to a point where we think we will need to scale beyond our initial set of boostrap nodes.

For your second point, this isn't something I thought we were looking into, but it would be done on the ipfs daemon, not the http client, so implementation would depend on how and where that's being run. Because ipfs is modular, though, it's not difficult to swap out implementations of libp2p components such as bitswap.

**Comment by zachferland** [comment]
Very nice having the data! js bitswap is as "dumb" as expected hah

Think 1 could work, also have an alternative below that might have less dependencies (infra, runtime, clients, etc), and runs more adjacent. A mix of mitigations you listed above.

Could implement a libp2p discovery service for "load balancing" clusters. A main aim here being to not need clients to know anything about any particular infra and have that logic with service provider. It would just be passed as a module (provider and clients) and implemented as a lib2p protocol. Basically a cluster could have a static libp2p node that runs a limited set of services (mostly just discovery, probs doesnt need ipfs even). And this could be more traditionally load balanced (ideally simple since running so few services), so that all clients could have one connection here. This would be the multiaddress that all clients connect to still. 

On the provider side this discovery protocol would just need to know the list of available multiaddress in cluster. Clients would connect over this protocol and be sent 1 or more mulitaddress (round robin or other logic later). Probably would have to blacklist rest of list possibly.  

**Pluses**
- clients dont  need to know anything about infra, less re configuration when not connecting to our infra
- pretty good interface for infra providers, just have to  run this additional discovery node, and be able to export list of current peer ids through some "service" from their current infra. 

**Minuses** 
- maybe too slow, another round trip 
- maybe too many assumptions about infra, (but discovery "load balancing" logic could be modified or take modules, and some infra configurations will slower/faster, but nothing should block) 

---

For #2 

yeah if like the mini/specific graphsync, then that can be load balanced a bit more easily and would take most load off nodes. To be more general (or native) i think it would still need a discovery service (or way to manage connections, like above). So that it doesn't have to rely on our own cid resolving in our cluster. 

It would likely still use bitswap in some form to get those CIDs. It would either use bitswap on client to resolve all the cids it was given or alternatively the entire dag compressed would be returned in response (instead of cids), then in that case the provider node would be bundling that and may use bitswap to get data within cluster if the data didnt all exist at one node
